/*
USER				
U_ID(PK)	VARCHAR2(100)		
U_PW	VARCHAR2(100)		
U_NAME	VARCHAR2(200)			
U_ADDRESS	VARCHAR2(300)
U_EMAIL		VARCHAR2(300)
U_BIRTHDAY	DATE

ORDER				
O_NUM(주문번호)		NUMBER
O_DATA(주문일)		DATE		
U_ID(FK)			VARCHAR2(100)		
P_NUM 상품번호(FK)	NUMBER



PRODUCT		
P_NUM상품번호(PK)	NUMBER
P_NAME상품명		VARCHAR2(100)	
P_PRICE가격		NUMBER	
P_COUNT재고		NUMBER
*/

CREATE TABLE "USER"(
	U_ID VARCHAR2(100) PRIMARY KEY,
	U_PW VARCHAR2(100),
	U_NAME VARCHAR2(200),
	U_ADDRESS VARCHAR2(300),
	U_EMAIL VARCHAR2(300),
	U_BIRTHDAY DATE
);

DROP TABLE "USER";

CREATE TABLE "PRODUCT"(
	P_NUM NUMBER PRIMARY KEY,
	P_NAME VARCHAR2(100),
	P_PRICE NUMBER,
	P_COUNT NUMBER
);

DROP TABLE "PRODUCT";

CREATE TABLE "ORDER"(
	O_NUM NUMBER PRIMARY KEY,
	O_DATA DATE,
	U_ID VARCHAR2(100),
	P_NUM NUMBER,
	CONSTRAINTS U_IDFK FOREIGN KEY(U_ID) REFERENCES "USER"(U_ID),
	CONSTRAINTS P_NUMFK FOREIGN KEY(P_NUM) REFERENCES "PRODUCT"(P_NUM)
);

DROP TABLE "ORDER";

