spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liM717IxZ2SKLZB1
            clientSecret: f2086746e3d4a426c1f02cef70b2fa2de0eab182
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user